- pom.xml
- src/main/java/fr/insee/eno/ws/config/OpenApiConfiguration.java
- src/main/java/fr/insee/eno/ws/controller/GenerationController.java
- src/main/java/fr/insee/eno/ws/controller/HomeController.java
- src/main/java/fr/insee/eno/ws/controller/IntegrationController.java
- src/main/java/fr/insee/eno/ws/controller/ParametersController.java
- src/main/java/fr/insee/eno/ws/controller/SimpleGenerationController.java
- src/main/java/fr/insee/eno/ws/controller/UtilController.java
- src/main/java/fr/insee/eno/ws/service/ParameterService.java
- src/main/resources/params/fr/business.xml
- src/main/resources/params/fr/default.xml
- src/main/resources/params/fr/household.xml
- src/main/resources/params/js/business.xml
- src/main/resources/params/js/default.xml
- src/main/resources/params/js/household.xml
- src/main/resources/params/odt/default.xml
- src/main/resources/params/pdf/business.xml
- src/main/resources/params/pdf/default.xml
- src/main/resources/params/pdf/household.xml
- General endpoint reorganisation
- adding new HomeController to redirect homepage to swagger ui
- adding new IntegrationController for Survey integration jobs
- modify StudyUnit to Context
> Update version 1.0.2

- pom.xml
- src/main/java/fr/insee/eno/ws/controller/GenerationController.java
- src/main/java/fr/insee/eno/ws/controller/IntegrationController.java
- src/main/java/fr/insee/eno/ws/controller/ParametersController.java
- src/main/resources/params/ddi/default.xml
- src/main/resources/params/fo/household.xml
Return acceptance and add paramters for loop and initialize variables.
> return acceptance

- .gitignore
- pom.xml
- src/main/resources/params/fodt/default.xml
- dev return Eno V2
- fodt simple generation questionnaire WS
> Acceptance

- pom.xml
- src/main/resources/params/lunatic-xml/default.xml
pagination : none --> question for ddi2LunaticXML default
> updating properties pagination ddi2lunaticXML (question) for queen visu

- pom.xml
- src/main/java/fr/insee/eno/ws/controller/UtilController.java
- Adding util to web-service to allow transformation from Lunatic XML into Lunatic Json
- Changing versions in pom to align with future release of Eno 2.2.7, Eno-WS goes to 1.2.9
>  Json-lunatic util and eno v2.2.7

- pom.xml
- src/main/java/fr/insee/eno/ws/controller/GenerationController.java
- src/main/java/fr/insee/eno/ws/controller/SimpleGenerationController.java
Addition of a parameter in the WS ddi2lunatic to leave the possibility of parsing or not the Xpath in VTL (if the chosen language is already in VTL: unnecessary parsing
> Dev xpath vtl switch

- pom.xml
- src/main/java/fr/insee/eno/ws/controller/SimpleGenerationController.java
- src/main/resources/params/lunatic-xml/business.xml
- src/main/resources/params/lunatic-xml/default.xml
- src/main/resources/params/lunatic-xml/household.xml
- Adding Pagination WS parameter to single generation ddi2lunatic
- Changing default parameter to business and default AddFilterResult --> true
> Dev visu pogues sequence

- src/main/resources/pdf/fonts/LiberationSans-LICENSE
> Licence of the LiberationSans font

- pom.xml
- src/main/java/fr/insee/eno/ws/controller/GenerationController.java
- src/main/java/fr/insee/eno/ws/controller/IntegrationController.java
- src/main/java/fr/insee/eno/ws/controller/IntegrationHouseholdController.java
- src/main/resources/params/lunatic-xml/business.xml
- src/main/resources/params/lunatic-xml/default.xml
- src/main/resources/params/lunatic-xml/household.xml
- version Lunatic-model : 2.2.3 
- version Eno 2.2.10
- Missing and addFilterResult
- Insee household integration WS
> Dev lunatic logement

- pom.xml
- src/main/resources/params/lunatic-xml/process/business.xml
> Dev params process

- pom.xml
- src/main/resources/params/lunatic-xml/capi-cati/default.xml
- src/main/resources/params/lunatic-xml/capi-cati/household.xml
- src/main/resources/params/lunatic-xml/cawi/default.xml
- src/main/resources/params/lunatic-xml/cawi/household.xml
Changing parameters
Queen et Stromae V2 : <CommentQuestion>false</CommentQuestion>
Queen <Control>false</Control> aussi
> update default params queen and stromaev2

- .github/workflows/ci-docker.yml
Add `latest` tag in "Publish register" step.
> Add latest tag in Docker publish

- src/main/java/fr/insee/eno/ws/controller/GenerationController.java
Modify code to trace errors with esa integration
> Check errors when zipping response with /questionnaire/ddi-2-xforms

- pom.xml
Dependencies update in Eno lib.
See InseeFr/Eno#747
> build: eno version 2.4.10

- .github/workflows/ci-docker.yml
- .github/workflows/tag-release.yml
- .github/workflows/test.yml
- pom.xml
> hotfix: saxon bug in eno lib

- .github/workflows/ci-docker.yml
- pom.xml
- src/main/java/fr/insee/eno/ws/controller/IntegrationController.java
- src/main/java/fr/insee/eno/ws/controller/IntegrationHouseholdController.java
- src/main/java/fr/insee/eno/ws/controller/SimpleGenerationController.java
Add info level logging entries in the beggining of controller methods.
Goal: show in the log that this request has been received by the service.
> refactor: add logging on controllers

- pom.xml
- https://github.com/InseeFr/Eno/pull/846
> feat: update fo household first page

- pom.xml
- src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java
Add a multi-model option in FO standard endpoint.
> feat: multi-model option in fo standard endpoint

- .github/workflows/ci-build.yml
- .github/workflows/ci-docker.yml
- .github/workflows/tag-release.yml
- .github/workflows/test.yml
- pom.xml
Eno:
- https://github.com/InseeFr/Eno/pull/901
Lunatic-Model:
- https://github.com/InseeFr/Lunatic-Model/pull/128
> fix: suggester

- pom.xml
- feat: dynamic table row controls
- fix: remove xhtml bold for clarification label
- fix: pairwise variable group
> build: bump eno lib to 2.9.2

- pom.xml
> build: update external dependencies

- pom.xml
- src/main/java/fr/insee/eno/ws/controller/GenerationCustomController.java
- src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java
Main change:
- #175 
\+
- small fix on json lunatic questionnaire extension (was xml instead of json in custom parameters endpoint)
- external dependencies update
> Next: Eno lib 2.9.2

- pom.xml
Fix on the roudabout feature done in Eno lib.
> fix: roundabout

- Dockerfile
- pom.xml
- dependencies update
- features and fixes: https://github.com/InseeFr/Eno/releases/tag/v2.10.0
> Next: 2.5.0

- .github/workflows/create-snapshot.yml
- README.md
- pom.xml
- src/test/java/fr/insee/eno/ws/service/QuestionnaireGenerationTest.java
- src/test/resources/transforms/simple-ddi.xml
Fix Jaxb issues cf. 
- https://github.com/InseeFr/Eno/pull/1115
- https://github.com/InseeFr/Eno/pull/1118
> Next: 2.5.1

- Dockerfile
- pom.xml
- dependencies update
- update Eno lib: https://github.com/InseeFr/Eno/releases/tag/v2.11.0
> Next: 2.6.0

- pom.xml
> feat: dynamic unit

- .github/workflows/create-release.yml
- pom.xml
- Eno lib 2.12.0 for the **dynamic unit** feature
- dependencies update
- improve release CI to write Eno lib version in GitHub release
> Next: 2.7.0

- pom.xml
> fix: dynamic unit in ddi

- pom.xml
> Next 2.7.4

- pom.xml
> build: eno version with updated dependencies

- pom.xml
> feat(eno core): mandatory ucq with detail in pogues to ddi

- pom.xml
cf.
- https://github.com/InseeFr/Eno/pull/1275
> feat(eno core): new logo reference in paper questionnaire

- eno-core/questionnaires/esem-2020-a00/fo/m1/form/form.fo
- eno-core/questionnaires/esem-2020-a00/parameters.xml
- eno-core/questionnaires/simpsons/fo/simpsons/form/form.fo
- eno-core/questionnaires/simpsons/parameters.xml
- eno-core/src/main/resources/xslt/outputs/fo/models.xsl
- eno-core/src/test/resources/ddi-to-fo/out.fo
- eno-core/src/test/resources/params/in-to-out/business/form.fo
- eno-core/src/test/resources/params/in-to-out/default/form.fo
avant :
On a un cadre dans lequel, si on a un libellé on l'affiche, sinon, on ne met rien (ou une zone de saisie)
Après :
Si on a un libellé, on l'affiche, sinon, on met un cadre dans lequel on ne met rien (ou une zone de saisie)
Le libellé est sorti de la zone  dévolue à la saisie (mais peut être restreint à une case de tableau par exemple)
> fix(fo): libellé de personnalisation sorti de la zone de saisie
